export interface Product {
  id: string
  name: string
  price: number
  image: string
  category: string
  description: string
  rating: number
  reviews: number
  inStock: boolean
  discount?: number
}

export const products: Product[] = [
  // Fresh Vegetables
  {
    id: "1",
    name: "Organic Tomatoes",
    price: 4.99,
    image: "../images/tomatoes.jpg",
    category: "Vegetables",
    description: "Fresh, ripe organic tomatoes perfect for salads and cooking",
    rating: 4.8,
    reviews: 245,
    inStock: true,
    discount: 10,
  },
  {
    id: "2",
    name: "Crispy Lettuce",
    price: 3.49,
    image: "../images/Lettuce.jpg",
    category: "Vegetables",
    description: "Crisp and fresh lettuce for your salads",
    rating: 4.6,
    reviews: 189,
    inStock: true,
  },
  {
    id: "3",
    name: "Bell Peppers Mix",
    price: 5.99,
    image: "../images/Peppers.jpg",
    category: "Vegetables",
    description: "Assorted bell peppers in red, yellow, and green",
    rating: 4.7,
    reviews: 156,
    inStock: true,
  },
  {
    id: "4",
    name: "Carrots Bundle",
    price: 2.99,
    image: "../images/Carrots.jpg?height=300&width=300",
    category: "Vegetables",
    description: "Sweet and crunchy carrots",
    rating: 4.5,
    reviews: 203,
    inStock: true,
  },

  // Fresh Fruits
  {
    id: "5",
    name: "Organic Apples",
    price: 6.99,
    image: "../images/Apples.jpg?height=300&width=300",
    category: "Fruits",
    description: "Crisp organic apples, perfect for snacking",
    rating: 4.9,
    reviews: 312,
    inStock: true,
    discount: 15,
  },
  {
    id: "6",
    name: "Bananas",
    price: 2.49,
    image: "../images/Bananas.jpg?height=300&width=300",
    category: "Fruits",
    description: "Fresh yellow bananas rich in potassium",
    rating: 4.7,
    reviews: 278,
    inStock: true,
  },
  {
    id: "7",
    name: "Strawberries",
    price: 7.99,
    image: "../images/Strawberies.jpg?height=300&width=300",
    category: "Fruits",
    description: "Sweet and juicy strawberries",
    rating: 4.8,
    reviews: 234,
    inStock: true,
  },
  {
    id: "8",
    name: "Oranges",
    price: 5.49,
    image: "../images/Oranges.jpg?height=300&width=300",
    category: "Fruits",
    description: "Juicy oranges full of vitamin C",
    rating: 4.6,
    reviews: 198,
    inStock: true,
  },

  // Dairy & Eggs
  {
    id: "9",
    name: "Organic Milk",
    price: 4.49,
    image: "../images/Milk.jpg?height=300&width=300",
    category: "Dairy",
    description: "Fresh organic whole milk",
    rating: 4.7,
    reviews: 267,
    inStock: true,
  },
  {
    id: "10",
    name: "Greek Yogurt",
    price: 5.99,
    image: "../images/yougart.jpg?height=300&width=300",
    category: "Dairy",
    description: "Creamy Greek yogurt, high in protein",
    rating: 4.8,
    reviews: 289,
    inStock: true,
  },
  {
    id: "11",
    name: "Cheddar Cheese",
    price: 8.99,
    image: "../images/Cheese.jpg?height=300&width=300",
    category: "Dairy",
    description: "Aged cheddar cheese with rich flavor",
    rating: 4.9,
    reviews: 156,
    inStock: true,
  },
  {
    id: "12",
    name: "Free Range Eggs",
    price: 6.49,
    image: "../images/Eggs.jpg?height=300&width=300",
    category: "Dairy",
    description: "12 free-range organic eggs",
    rating: 4.8,
    reviews: 342,
    inStock: true,
  },

  // Bakery
  {
    id: "13",
    name: "Whole Wheat Bread",
    price: 3.99,
    image: "../images/White Bread.jpg?height=300&width=300",
    category: "Bakery",
    description: "Fresh whole wheat bread baked daily",
    rating: 4.7,
    reviews: 201,
    inStock: true,
  },
  {
    id: "14",
    name: "Croissants",
    price: 4.99,
    image: "../images/bread.jpg?height=300&width=300",
    category: "Bakery",
    description: "Buttery croissants, pack of 4",
    rating: 4.8,
    reviews: 178,
    inStock: true,
  },
  {
    id: "15",
    name: "Sourdough Bread",
    price: 5.49,
    image: "../images/White Bread.jpg?height=300&width=300",
    category: "Bakery",
    description: "Artisan sourdough with tangy flavor",
    rating: 4.9,
    reviews: 145,
    inStock: true,
  },
  {
    id: "16",
    name: "Blueberry Muffins",
    price: 6.99,
    image: "../images/Muffin.jpg?height=300&width=300",
    category: "Bakery",
    description: "Fresh blueberry muffins, pack of 6",
    rating: 4.6,
    reviews: 167,
    inStock: true,
  },

  // Pantry
  {
    id: "17",
    name: "Olive Oil",
    price: 12.99,
    image: "../images/Olive oil.jpg?height=300&width=300",
    category: "Pantry",
    description: "Extra virgin olive oil, 500ml",
    rating: 4.9,
    reviews: 234,
    inStock: true,
  },
  {
    id: "18",
    name: "Pasta",
    price: 2.49,
    image: "../images/pasta.jpg?height=300&width=300",
    category: "Pantry",
    description: "Premium Italian pasta, 500g",
    rating: 4.7,
    reviews: 189,
    inStock: true,
  },
  {
    id: "19",
    name: "Rice",
    price: 3.99,
    image: "../images/Rice.jpg?height=300&width=300",
    category: "Pantry",
    description: "Jasmine rice, 2kg bag",
    rating: 4.8,
    reviews: 212,
    inStock: true,
  },
  {
    id: "20",
    name: "Honey",
    price: 9.99,
    image: "../images/Honey.jpg?height=300&width=300",
    category: "Pantry",
    description: "Raw organic honey, 500g",
    rating: 4.9,
    reviews: 267,
    inStock: true,
  },

  // Beverages
  {
    id: "21",
    name: "Orange Juice",
    price: 4.99,
    image: "../images/orange juice.jpg?height=300&width=300",
    category: "Beverages",
    description: "Fresh squeezed orange juice, 1L",
    rating: 4.6,
    reviews: 178,
    inStock: true,
  },
  {
    id: "22",
    name: "Coffee Beans",
    price: 11.99,
    image: "../images/Coffe beans.jpg?height=300&width=300",
    category: "Beverages",
    description: "Premium arabica coffee beans, 500g",
    rating: 4.8,
    reviews: 289,
    inStock: true,
  },
  {
    id: "23",
    name: "Green Tea",
    price: 6.99,
    image: "../images/green tea.jpg?height=300&width=300",
    category: "Beverages",
    description: "Organic green tea, 20 bags",
    rating: 4.7,
    reviews: 145,
    inStock: true,
  },
  {
    id: "24",
    name: "Almond Milk",
    price: 3.99,
    image: "../public/images/Almond milk.jpg?height=300&width=300",
    category: "Beverages",
    description: "Unsweetened almond milk, 1L",
    rating: 4.5,
    reviews: 156,
    inStock: true,
  },
]

export const categories = ["All", "Vegetables", "Fruits", "Dairy", "Bakery", "Pantry", "Beverages"]
